<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>9c8e86aa-e390-455a-9598-4d5c8f901776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnUpdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnUpdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80846bc9-8b75-4cf9-9e38-ac99c353348e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8504a1bf-be16-4159-9aad-1e9cde9f44e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary  btn-round</value>
      <webElementGuid>be678363-22e8-42b8-aa30-bfaed5a9a3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnUpdate</value>
      <webElementGuid>3c0d1b95-85f2-47a7-b04b-65badecffdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>380860d4-8383-425b-be2a-033486359595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>update</value>
      <webElementGuid>488d0ae5-0bb6-4362-bd17-7cbb50913615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                
                                                Update
                                            </value>
      <webElementGuid>16c8e93a-690e-4dfa-8e20-e0f49096a557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUpdate&quot;)</value>
      <webElementGuid>154e9f3c-2c4d-4239-82e0-06650098ef2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnUpdate']</value>
      <webElementGuid>c7f6976f-ed54-4de3-b220-d841a56bbb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-profile-1']/div/div[2]/div[9]/button</value>
      <webElementGuid>97802f31-9556-47a5-a010-196489b173d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New MSID'])[1]/following::button[1]</value>
      <webElementGuid>697572f9-1db0-4b5a-9594-1d1ae50775d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New SIMID'])[1]/following::button[1]</value>
      <webElementGuid>5589864c-b696-4fce-bf84-c6e5b55f4ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update']/parent::*</value>
      <webElementGuid>dc183409-2c88-408e-bd8b-26fb5059cf0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button</value>
      <webElementGuid>b1be81b4-0747-43be-8591-783fa3dcf1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnUpdate' and @name = 'search' and (text() = '
                                                
                                                Update
                                            ' or . = '
                                                
                                                Update
                                            ')]</value>
      <webElementGuid>3a9a010b-a530-4e34-916f-7b9439023b9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
