<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnterOldMSID</name>
   <tag></tag>
   <elementGuidId>102c2024-7819-4869-a832-3f422991c7af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtMsId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMsId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ce7916d-4f93-4fc3-ab02-81fd61d235c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6ae068c1-91c9-462f-9525-7cd0354addd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMsId</value>
      <webElementGuid>1f4e758f-042d-4f6d-a41a-dffe4ca1b8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtMsId</value>
      <webElementGuid>2782a905-410c-4b1f-8312-2ed067913ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d9eec0c-bdb2-4fb9-988b-f521497b3e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMsId&quot;)</value>
      <webElementGuid>256237a8-4f37-48ce-be82-41eecdcc51fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMsId']</value>
      <webElementGuid>855b85fd-0ef6-4ef8-a61f-bad96bd06560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//span[@id='signup']/input)[2]</value>
      <webElementGuid>687a0fa2-5b61-489f-8fee-f4175a304dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/span/input</value>
      <webElementGuid>fbbb34d3-420e-4b52-8c60-5f6a6c8f50fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtMsId' and @name = 'txtMsId' and @type = 'text']</value>
      <webElementGuid>a410444a-4fd5-463b-afb3-58f11893029b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
