<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnterNewMSID</name>
   <tag></tag>
   <elementGuidId>d95b1c3a-ac89-4608-8a12-d612414c82ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSimId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSimId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c77b9d27-b6b9-47d5-82f9-abacfff7c7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>317bb485-a970-48ea-85de-bf3886645faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSimId</value>
      <webElementGuid>a03f89e0-ad0c-45fa-bb4a-126266260b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSimId</value>
      <webElementGuid>8a6325e3-1b2f-41b2-a0b8-afe245d2b246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30c22152-af6a-43da-b5a3-a46325858cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSimId&quot;)</value>
      <webElementGuid>c850d7cf-d126-422d-81b0-d81553959c46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSimId']</value>
      <webElementGuid>773fa8ba-25e9-4d14-a2d6-dcf55391b8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='signup']/input</value>
      <webElementGuid>46acd523-0831-401b-ba40-585c5fd1ec04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>8b5cdb08-f64e-43b3-81bd-6cd7aa8bed95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtSimId' and @name = 'txtSimId' and @type = 'text']</value>
      <webElementGuid>1752e07c-4dd7-4f47-acc8-e9ce37b2bab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
