<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AdminPortal</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c4a8d54c-bc67-4f7e-925f-39d6f1fdaa8f</testSuiteGuid>
   <testCaseLink>
      <guid>b4c9c6f9-ffb6-4fb1-aaef-0a7439b6b91e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b2a474dd-6edc-403f-bd20-2c4b8182b76e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/dataDriven</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3466f91-b8eb-4b61-89c1-e8972d786784</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d13d3ec0-d9d1-490e-98d1-91e89c9fea8d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
