<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnterMobileNumber</name>
   <tag></tag>
   <elementGuidId>57d9f7a1-f751-4326-bc43-b7ccf2716d99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtMobileNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMobileNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23357ff1-fbe8-4130-96bc-60ef0b0eb525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c41fc0c4-6cb6-4f52-8b62-8ef83d013e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eb2f272e-b3ea-4b07-b2e6-e943f85dad34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMobileNumber</value>
      <webElementGuid>6abb9659-7713-42a5-a8a4-073f5aedf2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtMobileNumber</value>
      <webElementGuid>dc6d5c0a-f589-4429-9005-9c451975272b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>00959979933122</value>
      <webElementGuid>a6d19649-f232-4136-83aa-136e0321f437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36a2c8d6-f3cf-48ce-82ff-98d5b97de893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMobileNumber&quot;)</value>
      <webElementGuid>938f11f1-1bff-46d6-b037-5a00a7fdb65f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMobileNumber']</value>
      <webElementGuid>3021ac35-6ae6-42da-ba46-1907083bb939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/div/div[2]/form/div[2]/div/div/div/div[3]/input</value>
      <webElementGuid>7e66cfc1-c830-40fa-9713-32187b09b738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>0a3d60ce-b2c7-4547-a1f1-6ffb9acd3f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtMobileNumber' and @name = 'txtMobileNumber' and @placeholder = '00959979933122' and @type = 'text']</value>
      <webElementGuid>e29f785a-53c3-4c9e-8e4a-d019cb0960d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
