<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MobileNumber_txtMobileNumber</name>
   <tag></tag>
   <elementGuidId>7f86e3c8-45c2-4364-ae50-172d618abb51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMobileNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtMobileNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fff6586d-b7b8-4854-9ae8-7ceffadec035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0db335a3-53b5-4f62-afc2-44986a81a118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>905a58fd-35e2-4294-90d9-d2e94a2f1eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMobileNumber</value>
      <webElementGuid>7ab7a1dc-e9a6-4a69-b7a2-53db81926006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtMobileNumber</value>
      <webElementGuid>cdf25a65-d39b-41af-8ee3-0b1519faf1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>00959979933122</value>
      <webElementGuid>17da2a8b-6041-472f-ad0d-787a90f4489a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0ea2ebc-6e09-4720-8bbf-ca6adaf74c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMobileNumber&quot;)</value>
      <webElementGuid>192dbd91-8497-41ec-bd20-8a1198f67727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMobileNumber']</value>
      <webElementGuid>f9a52c46-a481-4631-8e9e-233b1f1fd305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/div/div[2]/form/div[2]/div/div/div/div[3]/input</value>
      <webElementGuid>622e593e-013d-4d9d-8685-3341fa4d3d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>2203e93c-820d-4718-b308-123bf5e2d5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtMobileNumber' and @name = 'txtMobileNumber' and @placeholder = '00959979933122' and @type = 'text']</value>
      <webElementGuid>7ccc707a-4ee1-454e-8221-ff23c379aa06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
