<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginButton</name>
   <tag></tag>
   <elementGuidId>34adf155-3092-439d-98f0-c31952c5096b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.bigger-110</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-box']/div/div/form/fieldset/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8797293e-f4b1-4759-8366-42c60cf24bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bigger-110</value>
      <webElementGuid>10bb484c-3914-4ef1-8118-2637fcad7c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>91518427-c62d-4841-9e9f-7e0430c587da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-box&quot;)/div[@class=&quot;widget-body&quot;]/div[@class=&quot;widget-main&quot;]/form[@class=&quot;form-horizontal&quot;]/fieldset[1]/div[@class=&quot;clearfix&quot;]/button[@class=&quot;width-35 pull-right btn btn-sm btn-primary&quot;]/span[@class=&quot;bigger-110&quot;]</value>
      <webElementGuid>f1ee144a-7a36-4925-ae2f-085309e68869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-box']/div/div/form/fieldset/div[2]/button/span</value>
      <webElementGuid>00e5935c-8482-4568-85d0-4113bbf6cd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember Me'])[1]/following::span[1]</value>
      <webElementGuid>5ef02e3e-5a29-4958-a6f5-66f401bbe563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Me!'])[1]/preceding::span[2]</value>
      <webElementGuid>2f536194-829a-4243-a148-f3772e33e051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>c6727981-d1a0-4062-804f-154c419175cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>92ecf52c-2f14-48d3-84b2-3ec53f4358cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>2d3b252f-0195-45f6-8234-64ea3182bb7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
