<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Device</name>
   <tag></tag>
   <elementGuidId>ec173dc3-7e0e-427a-8421-f4adf18897bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar']/ul/li[4]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.active.open > a.dropdown-toggle > span.menu-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>551d1cd6-54b0-44e1-867e-b2447f6d3b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>c3cab9fb-f6b7-4fbf-a855-8fbea568e3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Device </value>
      <webElementGuid>f0884e9e-eed6-43d3-ab62-93d2f6a2a2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/ul[@class=&quot;nav nav-list&quot;]/li[@class=&quot;active open&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;menu-text&quot;]</value>
      <webElementGuid>508e9e36-b639-4e91-8259-fb892318b620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar']/ul/li[4]/a/span</value>
      <webElementGuid>9009ff61-e880-4c46-8578-aae51c97d0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Device']/parent::*</value>
      <webElementGuid>252632be-037e-46bd-aec4-6d77eb63ee2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>acf26950-d40d-4ec5-be74-0cd0e5f0919b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '  Device ' or . = '  Device ')]</value>
      <webElementGuid>ef731bd5-ecf7-488c-86a0-5c002b657683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
