<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnterUDID</name>
   <tag></tag>
   <elementGuidId>e80751bc-3adb-45ac-b3cc-a1a3dcd1fa08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Otp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Otp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb999b2e-5701-4e91-a40a-3eb1e97cf5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>62e591ab-511c-4fee-8444-7c2b68f674b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Otp</value>
      <webElementGuid>c761b12b-d5b7-40ef-b8e1-fd54977df52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Otp</value>
      <webElementGuid>ce870a73-1360-4f1f-b090-33b38d077650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#361DBAE6-C780-0CA9-BE5C-B6357A6319E3</value>
      <webElementGuid>3076ecf6-8a79-4ed8-941e-9e47b6125496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24dbd0e2-07b5-4f62-b25c-eb09636bcc42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Otp&quot;)</value>
      <webElementGuid>85f71d3d-e812-4f49-8427-9ee8b5450ce4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Otp']</value>
      <webElementGuid>0d1af421-4b5a-4e71-8736-c839dd8de849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/div/div[2]/form/div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>39307dd0-fc4f-4402-9780-cca900d4f287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>198d2a4f-f9e4-42b3-a225-0a9be5f21dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Otp' and @name = 'Otp' and @placeholder = '#361DBAE6-C780-0CA9-BE5C-B6357A6319E3' and @type = 'text']</value>
      <webElementGuid>f49a4989-68f9-40b3-81df-e557d6516092</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
