<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnterPhoneNumber</name>
   <tag></tag>
   <elementGuidId>33b46047-ccc9-4862-88bf-eb93186dc521</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PhoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PhoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0f08847-0256-4139-a9b7-ff4a44bfc6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5626b5d3-9bb7-449f-90e8-2b142a41e937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PhoneNumber</value>
      <webElementGuid>b6a0eccd-cbcb-4aee-8257-221ef056e399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneNumber</value>
      <webElementGuid>8d965f49-3824-4c41-8fd1-2217633da029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>00959979933122</value>
      <webElementGuid>e24b1cab-4185-4423-a8cc-3a4a1c277a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>734a337d-2c0b-45ca-872e-8c68569c0ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PhoneNumber&quot;)</value>
      <webElementGuid>cc36fcb6-b97f-4582-ba3b-cdb470b1ea4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PhoneNumber']</value>
      <webElementGuid>3f19ef12-4c6e-4f2c-8230-52022da87b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/div/div[2]/form/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>6399ba8b-514d-4243-8bd6-ad955a6f217f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4c6c56e3-47ed-483c-a45f-50ee1c408a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PhoneNumber' and @name = 'PhoneNumber' and @placeholder = '00959979933122' and @type = 'text']</value>
      <webElementGuid>fdfb1855-2655-4ef6-ae4a-07aefef7f62a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
