<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IOS Otp</name>
   <tag></tag>
   <elementGuidId>1e5af096-d45a-4e00-955c-cefd714cee58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(9) > a > span.menu-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar']/ul/li[9]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84d473ea-4c60-43fb-b00d-30626b58ad5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>0ec0a996-408c-43e6-af7a-ee44160ccce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> IOS Otp </value>
      <webElementGuid>204e7405-43e4-45d8-ae64-9f86e1536796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/ul[@class=&quot;nav nav-list&quot;]/li[9]/a[1]/span[@class=&quot;menu-text&quot;]</value>
      <webElementGuid>71314e39-1ba9-41e2-bc96-13b62e0a8a26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar']/ul/li[9]/a/span</value>
      <webElementGuid>81ff446b-278e-4f2d-9980-a1de51c93a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ocr Scan Data'])[1]/preceding::span[1]</value>
      <webElementGuid>1195dea3-f1b5-42c7-a0f5-4cd15738e355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IOS Otp']/parent::*</value>
      <webElementGuid>3b1abc61-607d-4090-b430-23f70424631c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a/span</value>
      <webElementGuid>bb059351-7fcd-4fee-b263-6874b73a54c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' IOS Otp ' or . = ' IOS Otp ')]</value>
      <webElementGuid>76e935c3-ecb6-4044-8087-5b592243869f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
