<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>d673e8b4-0942-4df2-867b-a6354a696642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-box']/div/div/form/fieldset/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.bigger-110</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4def512a-10a1-423e-9562-0593588e8aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bigger-110</value>
      <webElementGuid>ee9e3c9c-2b29-447b-9de0-3839d355e5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>24f597a5-164c-4655-965c-ff456fd2a931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-box&quot;)/div[@class=&quot;widget-body&quot;]/div[@class=&quot;widget-main&quot;]/form[@class=&quot;form-horizontal&quot;]/fieldset[1]/div[@class=&quot;clearfix&quot;]/button[@class=&quot;width-35 pull-right btn btn-sm btn-primary&quot;]/span[@class=&quot;bigger-110&quot;]</value>
      <webElementGuid>c73397bc-c628-49d2-81eb-64504ddea396</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-box']/div/div/form/fieldset/div[2]/button/span</value>
      <webElementGuid>3c1f5d76-f514-4d5f-83be-431c28b671fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember Me'])[1]/following::span[1]</value>
      <webElementGuid>dd7e78ed-930c-4796-9b76-b053f9e64238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Me!'])[1]/preceding::span[2]</value>
      <webElementGuid>95f5390d-f4ed-4d57-8d1e-3ffbc1911491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>3568ff23-12d9-4dfe-8a3f-31a8b6c36bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>b36db580-08cd-43c0-a077-217b6b08c17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>446b4a26-9aa3-4c66-baa0-ca5b36429563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
