<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtUserName</name>
   <tag></tag>
   <elementGuidId>5f1508ae-9e06-4d96-88a8-cbcdd3679ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtUserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af61d62d-d973-46f3-a897-bb824247d727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2affab4-22d7-49be-ad4f-716fad80cbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7787ac33-6493-4388-9268-db5e415e149b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtUserName</value>
      <webElementGuid>40062460-b5ea-4cb6-b530-c8ae756d6e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUserName</value>
      <webElementGuid>1ff68bc8-4a63-448e-b660-6f49205dc3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username / Email </value>
      <webElementGuid>d49b7dff-b9f2-4765-b417-3fc330ae9d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUserName&quot;)</value>
      <webElementGuid>9cad9833-48bc-4686-a04a-4463e6830f0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtUserName']</value>
      <webElementGuid>be9b9b29-ba3d-473f-b0fb-57e79ecdf953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-box']/div/div/form/fieldset/label/span/input</value>
      <webElementGuid>c2233b65-7347-4f3a-9516-34e22c880e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>93171a5d-b399-4c94-9ff5-a15ed753070b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtUserName' and @id = 'txtUserName' and @placeholder = 'Username / Email ']</value>
      <webElementGuid>20f69d4c-8c5f-466b-917c-d650cd2d09c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
